Hw1
KatyaKos/Java_HW_16-17 pull request #2
Opened 2016-09-19 10:58 UTC by KatyaKos

AU Katya Koshchenko. HashTable1 Java HW.

2016-09-23 11:05 UTC, yurii-litvinov commented on hw1/src/me/spbau/katyakos/java/hw_16_17/hw1/HashTable/HashTable.java
> +    public boolean contains(String key) {
методы обычно разделяют пустыми строками

2016-09-23 11:05 UTC, yurii-litvinov commented on hw1/src/me/spbau/katyakos/java/hw_16_17/hw1/HashTable/HashTable.java
> +        return false;
это можно записать просто как return null != found;

2016-09-23 11:18 UTC, yurii-litvinov commented on hw1/src/me/spbau/katyakos/java/hw_16_17/hw1/HashTable/HashTable.java
> +        }
в конструкторе точно такой же код, имеет смысл просто в конструкторе вызывать clear (правда, тогда лучше сделать его final, чтобы наследники не могли его переопределить)

2016-09-23 11:25 UTC, yurii-litvinov commented on hw1/src/me/spbau/katyakos/java/hw_16_17/hw1/HashTable/List/Node.java
> +    protected Node next;
а зачем он protected?

2016-09-23 11:26 UTC, yurii-litvinov commented on hw1/src/me/spbau/katyakos/java/hw_16_17/hw1/HashTable/List/Node.java
> +    public void setNext(Node nxt) {
вообще, если есть конфликт имени параметра метода и поля, лучше использовать this. Параметр --- штука, более видимая, чем поле, поэтому он всегда должен называться возможно более по-человечески

2016-09-23 11:35 UTC, yurii-litvinov requested changes
всё ок, но есть мелкие замечания, поправьте, пожалуйста. и надо более содержательные комментарии к (будущим) коммитам :)

2016-10-02 11:05 UTC, yurii-litvinov approved these changes

2016-10-02 11:05 UTC, yurii-litvinov commented on hw1/src/me/spbau/katyakos/java/hw_16_17/hw1/HashTable/HashTable.java
> +    private int getHash(String key) {
вообще, в Java каждый объект имеет метод hashCode, который при желании можно переопределить для своего объекта, так что обычно пользуются им, а не делают свои хеш-функции. правда, он возвращает произвольное (в т.ч. отрицательное) число, которое надо загнать в диапазон допустимых значений bucket-ов хеш-таблицы

2016-10-02 11:05 UTC, yurii-litvinov commented
почему у Вас коммиты без комментариев, кстати?

2016-10-02 11:47 UTC, KatyaKos commented
Я просто Tortoise SVN пользуюсь, а там нет прям отдельного этапа "комментарий к коммиту", так что я забываю постоянно.

2016-10-02 11:48 UTC, merged

2016-10-02 11:54 UTC, yurii-litvinov commented
TortoiseGit? Там же наоборот, она не даст сделать коммит, если поле comment пусто.

2016-10-02 12:02 UTC, KatyaKos commented
Не знаю, может старая или другая версия, но моему все равно.

2016-10-02 12:04 UTC, yurii-litvinov commented
в крайнем случае, есть галка "Amend last commit", дописываете забытый комментарий и делаете git push -f ("Force" в тортузе). это плохо, потому что историю коммитов лучше не менять, но это лучше, чем коммиты без комментариев

2016-10-02 12:04 UTC, KatyaKos commented
Ну просто постараюсь не забывать тогда.

2016-10-02 12:06 UTC, yurii-litvinov commented
лучше решать проблемы не административными методами ("постараюсь не забывать"), а инструментальной поддержкой, потому что всё равно забудете. может, поставите новую версию TortoiseGit-а?

2016-10-02 12:36 UTC, KatyaKos commented
Хорошо.